// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ws from "ws";

function isOpen(ws) {
  return ws.readyState === Ws.WebSocket.OPEN;
}

function make(prim) {
  return new Ws.WebSocket(prim);
}

function send(prim0, prim1) {
  prim0.send(prim1);
}

function close(prim) {
  prim.close();
}

function addOpenListener(prim0, prim1) {
  prim0.addEventListener("open", prim1);
}

function addCloseListener(prim0, prim1) {
  prim0.addEventListener("close", prim1);
}

function addMessageListener(prim0, prim1) {
  prim0.addEventListener("message", prim1);
}

function addErrorListener(prim0, prim1) {
  prim0.addEventListener("error", prim1);
}

export {
  make ,
  isOpen ,
  send ,
  close ,
  addOpenListener ,
  addCloseListener ,
  addMessageListener ,
  addErrorListener ,
}
/* ws Not a pure module */
