// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AcLive__Session from "./AcLive__Session.mjs";
import * as Node__WebSocket from "./websocket/Node__WebSocket.mjs";
import * as Tauri__WebSocket from "./websocket/Tauri__WebSocket.mjs";
import * as WebAPI__WebSocket from "./websocket/WebAPI__WebSocket.mjs";

function makeWebAPISession(config) {
  return AcLive__Session.make(WebAPI__WebSocket, config);
}

function makeNodeSession(config) {
  return AcLive__Session.make(Node__WebSocket, config);
}

function makeTauriSession(config) {
  return AcLive__Session.make(Tauri__WebSocket, config);
}

var Message;

var Session;

export {
  Message ,
  Session ,
  makeWebAPISession ,
  makeNodeSession ,
  makeTauriSession ,
}
/* AcLive__Session Not a pure module */
