// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AcLive__Session from "../AcLive__Session.bs.mjs";
import * as Tauri__WebSocket from "../websocket/Tauri__WebSocket.bs.mjs";

function makeSession(config) {
  return AcLive__Session.make(Tauri__WebSocket, config);
}

export {
  makeSession ,
}
/* AcLive__Session Not a pure module */
