// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AcLive__Session from "../AcLive__Session.bs.mjs";
import * as WebAPI__WebSocket from "../websocket/WebAPI__WebSocket.bs.mjs";

function makeSession(config) {
  return AcLive__Session.make(WebAPI__WebSocket, config);
}

export {
  makeSession ,
}
/* AcLive__Session Not a pure module */
